[package]
name = "ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icmp = "0.3.0"
etherparse = "0.10.1"
packet = "0.1"
